### ISSUE TITLE
harpoon.yml code/doc inconsistency.

### ISSUE THREAD

**Issue by jonhiggs** [delfick/harpoon#16]
When ~/.harpoon.yml exists it complains when you don't have ./harpoon.yml. The documentation indicates that that should be valid. Is the documentation or the code wrong?

**Comment by delfick** [comment]
The documentation is misleading I'd say :p 

It should probably say that a config file is mandatory because it doesn't make sense to not have a config file.

The unfortunate thing is when the config doesn't exist it'll display a traceback.

On further thought on this I have an idea on how to make it not display a traceback, I'll make a change later on.

**Comment by braidenjudd** [comment]
Just use straight cloud formation 😎

**Comment by delfick** [comment]
@braidenjudd you seem to be confusing this project with bespin.readthedocs.org....

troll officially failed :)

**Comment by delfick** [comment]
I've added a couple commits to the refactor branch.

They'll become available once refactor has been merged into master
