### ISSUE TITLE
Retire gitmit

### ISSUE THREAD

**Issue by CaseyLeask** [delfick/harpoon#22]
Now that caching ignores mtime, we might be able to retire gitmit
https://github.com/docker/docker/issues/4351#issuecomment-112164613

**Comment by delfick** [comment]
I'll certainly have a look and see if that's true (going by the comment I assume it is) but that comment was a year ago and I haven't realised since you pointed it out just now.

I'll also probably keep it in for anyone actually using harpoon with an older version of docker and will remove it in the future.

For now, if you don't want to spend cycles computing the modified time from git, just set the context.use_git_timestamps option to False.

Note that very little code would be removed as we still need git to remove files from the context that are ignored by .gitignore (git ignore semantics are much more complicated and flexible than docker ignore). 

Also we still need to find all the files for the exclude/inclusion options in the context.
